### ISSUE TITLE
Why is allow SQL set to off?

### ISSUE THREAD

**Issue by earthboundkid** [simonw/russian-ira-facebook-ads-datasette#2]
I wanted to do a select to see the `count(*)` for impressions with target including Baltimore. Obviously, I can still do it by cloning the repo and running the query locally, but it would be nice to do it on the site already live.

**Comment by simonw** [comment]
This was because I was paranoid about bad actors deliberately trying to bring down the site with malicious SQL queries. I probably over-thought that!
